do not use temp file

diff --git a/subdl b/subdl
--- a/subdl
+++ b/subdl
@@ -1,8 +1,6 @@
 #!/bin/sh
 
 usage="usage: ${0##*/} [-e episode] [-i imdbid] [-s season] [-l sublanguageid] [-n] [query]"
-tmpfile=$(mktemp /tmp/subdl-XXXXXX)
-trap 'rm "$tmpfile"' 0 1 15
 
 url_encode() {
 	# Query must be URL encoded to handle reserved characters.
@@ -11,14 +9,14 @@ url_encode() {
 }
 
 check_num() {
-	printf '%s' "$1" | grep '^[0-9]\+$' > /dev/null || {
+	printf '%s' "$1" | grep -q '^[0-9]\+$' || {
 		printf 'Season and episode must be natural numbers.\n'
 		exit 1
 	}
 }
 
 check_lang() {
-	printf '%s' "$1" | grep '^[a-z]\{3\}\(,[a-z]\{3\}\)*$' > /dev/null || {
+	printf '%s' "$1" | grep -q '^[a-z]\{3\}\(,[a-z]\{3\}\)*$' || {
 		printf 'Language code must be 3 letters.\n'
 		printf 'Multiple languages must be separated with a comma.\n'
 		exit 1
@@ -26,7 +24,7 @@ check_lang() {
 }
 
 check_imdbid() {
-	printf '%s' "$1" | grep '^[0-9]\{7\}$' > /dev/null || {
+	printf '%s' "$1" | grep -q '^[0-9]\{7\}$' || {
 		printf 'Imdbid must be 7 figures.\n'
 		printf 'Imdbid must exclude property prefix.\n'
 		exit 1
@@ -42,7 +40,6 @@ check_args() {
 }
 
 set_query() {
-	# Strip the location prefix if the query is a file.
 	if [ -f "$1" ]
 	then
 		url_encode "${1##*/}"
@@ -53,7 +50,6 @@ set_query() {
 }
 
 set_addr() {
-	# Print slash only when the relevant variable exists.
 	printf 'http://rest.opensubtitles.org/search%s%s%s%s%s'    \
 	       "${episode:+/episode-}${episode}"                   \
 	       "${imdbid:+/imdbid-}${imdbid}"                      \
@@ -62,50 +58,36 @@ set_addr() {
 	       "${sublanguageid:+/sublanguageid-}${sublanguageid}"
 }
 
-display_results() {
-	jq -e -j '
+parse_results() {
+	jq -e -r '
 		. |
 		if length == 0
 		then
-			"no result.\n" | halt_error
+			"No results found.\n" | halt_error
 		else
-			[[range(length) | tostring] ,
-			[.[].SubFileName] , [.[].SubLanguageID]] |
-			transpose | .[] | " " + .[0] + " [" + .[2] +
-			"]: " + .[1] | . + "\n"
+			.[] | [ .SubFileName + "\t" + .SubDownloadLink ] | .[]
 		end
-	' "$tmpfile" || {
-		# If there is a server error, the error message is displayed in
-		# plain text instead of JSON. This causes jq to fail parsing the
-		# server response. In that case the file is output to terminal
-		# to show the error.
-		cat "$tmpfile"
-		exit 1
+	'
+}
+
+get_num() {
+	[ -z "$num" ] && {
+		printf "Subtitle number (Ctrl-c to cancel): "
+		read -r num
+		check_num "$num"
+		[ "$num" -gt "$#" ] || [ "$num" -le 0 ] && {
+			printf 'Subtitle does not exist.\n'
+			exit 1
+		}
 	}
-}
-
-ask_num() {
-	printf "Subtitle number (Ctrl-c to cancel): "
-	read -r num
-	check_num "$num"
-}
-
-get_sub_info() {
-	# Get the first result (number zero) if '-n flag' is supplied.
-	# TODO: Check if the num exists
-	jq -j --argjson num "${num:-0}" '
-		.[$num] | [ .SubDownloadLink , "\t" , .SubFileName ] | .[]
-	' "$tmpfile"
 }
 
 while getopts ne:i:s:l: opt
 do
-	# Set variables from command line options. Also do sanity
-	# checks to not send an erronous request to the server.
 	case $opt in
 		n)
-			# Download the first result
-			dontask="1"
+			# Download the first result.
+			num=1
 			;;
 		e)
 			check_num "$OPTARG"
@@ -131,27 +113,31 @@ do
 done
 shift $(( OPTIND - 1 ))
 
-# Make sure that proper arguments are supplied.
 check_args "$@"
-
-# Define the 'query' and 'address' variables.
 query=$(set_query "$@")
 addr=$(set_addr)
 
-# Get the query response page from the server.
-curl -s -S -A 'TemporaryUserAgent' "$addr" > "$tmpfile"
+set --
+IFS=$(printf '\n\r')
+for line in $(curl -s -S -A 'TemporaryUserAgent' "$addr" | parse_results)
+do
+	set -- "$@" "$line"
+done
+unset IFS
 
-# Display list of available subtitles by parsing the server response.
-display_results
+[ "$#" -eq 0 ] && {
+	printf 'Error.\n'
+	exit 1
+}
 
-# Prompt for user input if '-n flag' is not provided.
-[ -z "$dontask" ] && ask_num
+# List subtitles for selection.
+printf '%s\n' "$@" | cut -f 1 | nl -w 4 -s ': '
 
-# Parse the query response page one more time to get the download URL and
-# the file name in a tab-delineated format.
-IFS='	' # IFS='\t'
-read -r dlurl filename << EOF
-$(get_sub_info)
+get_num
+
+IFS=$(printf '\t')
+read -r filename dlurl << EOF
+$(eval printf '%s' \"'$'"${num}"\")
 EOF
 
 # Finally download the subtitle file.
